/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * The classification details of the text.
 *
 */
class Classification {
  /**
   * Create a Classification.
   * @member {object} [category1]
   * @member {number} [category1.score] The category score.
   * @member {object} [category2]
   * @member {number} [category2.score] The category score.
   * @member {object} [category3]
   * @member {number} [category3.score] The category score.
   * @member {boolean} [reviewRecommended] The review recommended flag.
   */
  constructor() {
  }

  /**
   * Defines the metadata of Classification
   *
   * @returns {object} metadata of Classification
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Classification',
      type: {
        name: 'Composite',
        className: 'Classification',
        modelProperties: {
          category1: {
            required: false,
            serializedName: 'Category1',
            type: {
              name: 'Composite',
              className: 'Score'
            }
          },
          category2: {
            required: false,
            serializedName: 'Category2',
            type: {
              name: 'Composite',
              className: 'Score'
            }
          },
          category3: {
            required: false,
            serializedName: 'Category3',
            type: {
              name: 'Composite',
              className: 'Score'
            }
          },
          reviewRecommended: {
            required: false,
            serializedName: 'ReviewRecommended',
            type: {
              name: 'Boolean'
            }
          }
        }
      }
    };
  }
}

module.exports = Classification;
