/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The classification score details of the text. <a
 * href="https://aka.ms/textClassifyCategories">Click here</a> for more details
 * on category classification.
 *
 */
class Score {
  /**
   * Create a Score.
   * @member {number} [score] The category score.
   */
  constructor() {
  }

  /**
   * Defines the metadata of Score
   *
   * @returns {object} metadata of Score
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Score',
      type: {
        name: 'Composite',
        className: 'Score',
        modelProperties: {
          score: {
            required: false,
            serializedName: 'Score',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = Score;
